[project]
name = "end-to-end-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets[vision]>=5.0.0",
    "lightning>=2.6.5",
    "mlflow>=3.15.1",
    "notebook>=7.6.1",
    "optuna>=4.9.0",
    "optuna-integration>=4.9.0",
    "python-dotenv>=1.2.2",
    "sqlalchemy-utils>=0.42.1",
    "streamlit>=1.59.2",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "zenml[local,server]==0.96.3",
]
