[project]
name = "end-to-end-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets[vision]>=5.0.0",
    "optuna>=4.9.0",
    "streamlit>=1.59.2",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "zenml>=0.96.1",
]
